version: 1.0.{build}

branches:
#white list
  only: 
    - master

skip_commits:
  message: Updated biicode parents

install:
  - cinst biicode
  - cmd: bii --version

before_build:
  - cmd: cd \
  - cmd: bii init %project_name%
  - cmd: cd %project_name%
  - cmd: bii new %block_user%/%block_name%
    # copy files and folders
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\%block_user%\%block_name%\ /e
  - cmd: bii cpp:configure -G "Visual Studio 12"

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: cd bin
  - cmd: Maria_appveyor-test_main.exe
# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: bii user %block_user% -p %secured_passwd%
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME%  
  - if defined APPVEYOR_REPO_TAG_NAME bii publish --tag=%tag% --versiontag=%VERSION% 
  - if not defined APPVEYOR_REPO_TAG_NAME bii publish --tag=%dev_tag% 

on_success:
  #copy biicode.conf updated file
  - cmd: cd /%project_name%/blocks/%block_user%/%block_name%
  - cmd: move "biicode.conf" %APPVEYOR_BUILD_FOLDER%\
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  #config and push updated parents to GitHub
  - git config --global credential.helper store 
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git remote add neworigin %github_repo%
  - git checkout master
  - git config --global user.email %github_email%
  - git config --global user.name %github_user%
  - git add biicode.conf
  - git commit -m "Updated biicode parents"
  - git push neworigin master

environment:
  project_name:
    "myproject"
  block_user:
    "Maria"
  block_name:
    "appveyor-test"
  secured_passwd:
    secure: ZMvgETfLAUo7kISnvrinBA==
  access_token:
    secure: GdIDIRkmsM9blqS143lQErkxguMYgJBs74GzWw+lgzjvl/NoLs4ErcOZ2JBAEmkr
  tag:
    "STABLE"
  dev_tag:
    "DEV"
  github_user:
    "MariadeAnton"
  github_email:
    "maria.deanton@biicode.com"
  github_repo:
    "https://github.com/MariadeAnton/appveyor-test.git"
